# Generated by Django 4.2.1 on 2023-05-22 15:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0002_alter_task_deadline"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="tag",
            new_name="tags",
        ),
    ]
